environment:
  USER:
    secure: X

  PASS:
    secure: X

  matrix:
    - PYTHON: "C:/Python27"
      BUILD_ENV: "Visual Studio 14"
      BUILD_DIR: "build"
      PYTHON_VERSION: "2.7"
      NP_VERSION: "1.11.1"
      ENABLE_CONTRIB: 0

    - PYTHON: "C:/Python27-x64"
      BUILD_ENV: "Visual Studio 14 Win64"
      BUILD_DIR: "build64"
      PYTHON_VERSION: "2.7"
      NP_VERSION: "1.11.1"
      ENABLE_CONTRIB: 0

    - PYTHON: "C:/Python34"
      BUILD_ENV: "Visual Studio 14"
      BUILD_DIR: "build"
      PYTHON_VERSION: "3.4"
      NP_VERSION: "1.11.1"
      ENABLE_CONTRIB: 0

    - PYTHON: "C:/Python34-x64"
      BUILD_ENV: "Visual Studio 14 Win64"
      BUILD_DIR: "build64"
      PYTHON_VERSION: "3.4"
      NP_VERSION: "1.11.1"
      ENABLE_CONTRIB: 0

    - PYTHON: "C:/Python35"
      BUILD_ENV: "Visual Studio 14"
      BUILD_DIR: "build"
      PYTHON_VERSION: "3.5"
      NP_VERSION: "1.11.1"
      ENABLE_CONTRIB: 0

    - PYTHON: "C:/Python35-x64"
      BUILD_ENV: "Visual Studio 14 Win64"
      BUILD_DIR: "build64"
      PYTHON_VERSION: "3.5"
      NP_VERSION: "1.11.1"
      ENABLE_CONTRIB: 0

    - PYTHON: "C:/Python36"
      BUILD_ENV: "Visual Studio 14"
      BUILD_DIR: "build"
      PYTHON_VERSION: "3.6"
      NP_VERSION: "1.11.3"
      ENABLE_CONTRIB: 0

    - PYTHON: "C:/Python36-x64"
      BUILD_ENV: "Visual Studio 14 Win64"
      BUILD_DIR: "build64"
      PYTHON_VERSION: "3.6"
      NP_VERSION: "1.11.3"
      ENABLE_CONTRIB: 0

    - PYTHON: "C:/Python27"
      BUILD_ENV: "Visual Studio 14"
      BUILD_DIR: "build"
      PYTHON_VERSION: "2.7"
      NP_VERSION: "1.11.1"
      ENABLE_CONTRIB: 1

    - PYTHON: "C:/Python27-x64"
      BUILD_ENV: "Visual Studio 14 Win64"
      BUILD_DIR: "build64"
      PYTHON_VERSION: "2.7"
      NP_VERSION: "1.11.1"
      ENABLE_CONTRIB: 1

    - PYTHON: "C:/Python34"
      BUILD_ENV: "Visual Studio 14"
      BUILD_DIR: "build"
      PYTHON_VERSION: "3.4"
      NP_VERSION: "1.11.1"
      ENABLE_CONTRIB: 1

    - PYTHON: "C:/Python34-x64"
      BUILD_ENV: "Visual Studio 14 Win64"
      BUILD_DIR: "build64"
      PYTHON_VERSION: "3.4"
      NP_VERSION: "1.11.1"
      ENABLE_CONTRIB: 1

    - PYTHON: "C:/Python35"
      BUILD_ENV: "Visual Studio 14"
      BUILD_DIR: "build"
      PYTHON_VERSION: "3.5"
      NP_VERSION: "1.11.1"
      ENABLE_CONTRIB: 1

    - PYTHON: "C:/Python35-x64"
      BUILD_ENV: "Visual Studio 14 Win64"
      BUILD_DIR: "build64"
      PYTHON_VERSION: "3.5"
      NP_VERSION: "1.11.1"
      ENABLE_CONTRIB: 1

    - PYTHON: "C:/Python36"
      BUILD_ENV: "Visual Studio 14"
      BUILD_DIR: "build"
      PYTHON_VERSION: "3.6"
      NP_VERSION: "1.11.3"
      ENABLE_CONTRIB: 1

    - PYTHON: "C:/Python36-x64"
      BUILD_ENV: "Visual Studio 14 Win64"
      BUILD_DIR: "build64"
      PYTHON_VERSION: "3.6"
      NP_VERSION: "1.11.3"
      ENABLE_CONTRIB: 1

install:
- cmd: >-

    git submodule update --init --recursive

    C:\Python35\python.exe find_version.py

    "%PYTHON%/python.exe" -m pip install --upgrade pip

    "%PYTHON%/python.exe" -m pip install -r requirements.txt

build_script:
- build.cmd

before_test:
- cmd: >-

    cd ..

    "%PYTHON%/python.exe" -m pip install --no-index --find-links=%APPVEYOR_BUILD_FOLDER%\dist\ htcondor-python

test_script:
- cmd: >-

    cd %APPVEYOR_BUILD_FOLDER%\tests

    "%PYTHON%/python.exe" -m unittest test

artifacts:
- path: dist\*.whl
  name: wheels

deploy_script:
- cd %APPVEYOR_BUILD_FOLDER%

- echo "This is default build. Deplyoment will be done to to PyPI entry htcondor-python."

- if "%APPVEYOR_REPO_TAG%"=="true" ("%PYTHON%/python.exe" -m twine upload -u %USER% -p %PASS% --skip-existing dist/htcondor*) else (echo "Tag not set, deployment skipped.")
