from setuptools import setup
from setuptools.dist import Distribution
import io

# htcondor_version.py should be generated by running find_version.py
from htcondor_version import htcondor_version

package_name = "opencv-python"
long_description = ""
package_data = {}

with io.open('README.md', encoding="utf-8") as f:
    long_description = f.read()


class BinaryDistribution(Distribution):
    """ Forces BinaryDistribution. """

    def has_ext_modules(self):
        return True

    def is_pure(self):
        return False

# to be adjusted
setup(
    name=package_name,
    version=htcondor_version,
    url='https://github.com/bbockelm/htcondor-python',
    license='Apache 2.0',
    description='Wrapper package for HTCondor python bindings.',
    long_description=long_description,
    distclass=BinaryDistribution,
    packages=['htcondor'],
    package_data=package_data,
    maintainer="HTCondor Team",
    include_package_data=True,
    data_files=[("", ["LICENSE.md"])],
    install_requires="numpy>=%s" % numpy_version,
    classifiers=[
        'Development Status :: 5 - Production/Stable',
        'Environment :: Console',
        'Intended Audience :: Developers',
        'Intended Audience :: Education',
        'Intended Audience :: Information Technology',
        'Intended Audience :: Science/Research',
        'License :: OSI Approved :: MIT License',
        'Operating System :: MacOS',
        'Operating System :: Microsoft :: Windows',
        'Operating System :: POSIX',
        'Operating System :: Unix',
        'Programming Language :: Python',
        'Programming Language :: C++',
        'Programming Language :: Python :: Implementation :: CPython',
        'Topic :: Scientific/Engineering',
        'Topic :: Software Development',
    ]
)
